config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'home#index'

  resources :blog, only: [:index]
  resources :portfolio, only: [:index]
  resources :posts, except: [:index] do
    resources :comments
  end

  resources :youtube, only: :show

  match '(*any)', to: redirect(subdomain: ''), via: :all, constraints: {subdomain: 'www'}
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :show, Post, public: true

    if user.present? && user.admin?
        can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    before_save :set_avatar

    belongs_to :commentable, polymorphic: true
    has_many :comments, as: :commentable, dependent: :destroy
    
    validates_presence_of :name, :email, :content

    def set_avatar
        self.avatar = [:bill, :dog, :doge, :elon, :mark, :mark_2, :steve, :steve_2, :steve_3].sample
    end
end

app/models/post.rb
class Post < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged

    has_rich_text :content
    has_one_attached :banner

    belongs_to :user

    has_many :comments, as: :commentable, dependent: :destroy

    validates_presence_of :title, :content

    def banner_photo
        if self.banner.attached?
            self.banner
        else
            'bill_gates_phrase'
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  validates_presence_of :name, :email, :description

  enum role: [:admin, :normal]

  def perfil_photo
    if self.avatar.attached?
        self.avatar
    else
        'bill_gates_phrase'
    end
  end
end

app/models/youtube.rb
class Youtube
    include ActiveModel::Model
    include ActiveModel::Attributes
    include GlobalID::Identification
    include ActionText::Attachable

    attribute :id

    def self.find(id)
    new(id: id)
    end

    def thumbnail_url
    "http://i3.ytimg.com/vi/#{id}/maxresdefault.jpg"
    end

    def to_trix_content_attachment_partial_path
    "youtubes/thumbnail"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |e|
    respond_to do |format|
      format.html { redirect_to root_path, flash: { alert: "Você não possui autorização para acessar essa página!" } }
      format.json { render json: { success: false }, status: 401 }
    end
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
    skip_before_action :authenticate_user!
    
    def index
        @posts = Post.order(created_at: :DESC).page params[:page]
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_post, only: [:create]
    
    def index
    end

    def create
        @comment = Comment.new(comment_params)

        @comment.commentable = @post

        if @comment.save
            redirect_to request.referrer, notice: 'Comentário realizado com sucesso!'
        else
            redirect_to request.referrer, alert: 'Erro ao realizar comentário! Tente novamente mais tarde.'
        end
    end

    private

    def set_post
        @post = Post.friendly.find(params[:post_id])
    end

    def comment_params
        params.require(:comment).permit(:name, :email, :content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    skip_before_action :authenticate_user!
    
    def index
    end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :set_post, only: [:show, :edit, :update]

  def new
    authorize! :create, current_user
    @post = Post.new
  end

  def create
    authorize! :create, current_user
    @post = Post.new(posts_params)

    if @post.save
      redirect_to blog_index_path, notice: 'Post enviado com sucesso!'
    else
      redirect_to blog_index_path, alert: 'Erro ao enviar o post. Tente novamente mais tarde!'
    end
  end

  def edit
    authorize! :edit, current_user
  end

  def update
    authorize! :create, current_user

    if @post.update(posts_params)
      redirect_to blog_index_path, notice: 'Post atualizado com sucesso!'
    else
      redirect_to blog_index_path, alert: 'Erro ao atualizar post. Tente novamente mais tarde!'
    end
  end

  def show
    @comment = Comment.new
  end

  private

  def posts_params
    params.require(:post).permit(:title, :content, :slug, :banner, :user_id)
  end

  def set_post
    @post = Post.friendly.find(params[:id])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/youtube_controller.rb
class YoutubeController < ApplicationController
    def show
        @youtube = Youtube.new(id: params[:id])
        
        render json: {
            sgid: @youtube.attachable_sgid,
            content: render_to_string(partial: "youtubes/thumbnail", locals: { youtube: @youtube }, formats: [:html])
        }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags site: 'Blog Mainô - Wesley Padilha' %>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_path('/icons/favicon.ico') %>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-WL3T0055GJ"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-WL3T0055GJ');
    </script>
  </head>

  <body>
    <%= javascript_pack_tag 'turbolinks_audio_stop' %>
    
    <!-- Menu button -->
    <div class="mobile-lateral-menu">
      <button class="navbar-toggler">
        <%= image_tag 'programming' %>
      </button>
    </div>
    
    <div class="row application_row">
      <div class="col-md-3">
        <%= render 'shared/lateral_menu' %>
      </div>

      <div class="col-md-9">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_lateral_menu.html.erb
<%= javascript_pack_tag 'social_media_hover' %>
<%= javascript_pack_tag 'lateral_menu' %>

<div class="lateral_menu text-center">
    <div class="page-header mt-3 mb-3">
        <%= image_tag 'logo' %>
    </div>

    <%= render 'shared/users_option' %>

    <ul class="me-4">
        <li>
            <%= link_to root_path do %>
                HOME
            <% end %>
        </li>
        
        <li>
            <%= link_to blog_index_path, :"data-turbolinks" => false do %>
                BLOG
            <% end %>
        </li>

        <li>
            <%= link_to portfolio_index_path do %>
                SOBRE MIM
            <% end %>
        </li>
    </ul>

    <div class="social_media text-center">
        <div class="row">
            <div class="col youtube_div">
                <%= link_to 'https://www.youtube.com/channel/UCW7i1eD6-PVfHsBIfsGOkXA/videos' do %>
                    <%= image_tag 'youtube' %>
                <% end %>
            </div>

            <div class="col whatsapp_div">
                <%= link_to 'https://chat.whatsapp.com/JPuhmuzg4lrEu9sBKW3B6B' do %>
                    <%= image_tag 'whatsapp' %>
                <% end %>
            </div>  
        </div>

        <div class="youtube_phrase">
            Acesse nosso canal do <b>Youtube</b> para mais conteúdos!
        </div>

        <div class="whatsapp_phrase">
            Ou clique para entrar em nosso grupo no <b>Whatsapp</b>!
        </div>
    </div>
</div>

app/views/shared/_users_option.html.erb
<div class="dropdown user_perfil">
  <% if current_user %>
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
      <%= image_tag current_user.perfil_photo %>
    </button>

    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
      <li>
          <%= link_to 'Editar Perfil', edit_user_registration_path, class: "dropdown-item" %>
      </li>

      <li>
          <%= link_to 'Publicar Novo Post', new_post_path, class: "dropdown-item" if current_user.admin? %>
      </li>

      <li>
          <%= link_to 'Sair', destroy_user_session_path, class: "dropdown-item" %>
      </li>
    </ul>
  <% else %>
      <div class="sign_in">
        <%= link_to new_user_session_path do %>
          <%= image_tag 'anonymous' %>
        <% end %>
      </div>
  <% end %>
</div>