config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'home#index'

  resources :blog, only: [:index]
  resources :portfolio, only: [:index]
  resources :posts, except: [:index] do
    resources :comments
  end

  resources :youtube, only: :show

  match '(*any)', to: redirect(subdomain: ''), via: :all, constraints: {subdomain: 'www'}
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :show, Post, public: true

    if user.present? && user.admin?
        can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    before_save :set_avatar

    belongs_to :commentable, polymorphic: true
    has_many :comments, as: :commentable, dependent: :destroy
    
    validates_presence_of :name, :email, :content

    def set_avatar
        self.avatar = [:bill, :dog, :doge, :elon, :mark, :mark_2, :steve, :steve_2, :steve_3].sample
    end
end

app/models/post.rb
class Post < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged

    has_rich_text :content
    has_one_attached :banner

    belongs_to :user

    has_many :comments, as: :commentable, dependent: :destroy

    validates_presence_of :title, :content

    def banner_photo
        if self.banner.attached?
            self.banner
        else
            'bill_gates_phrase'
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  validates_presence_of :name, :email, :description

  enum role: [:admin, :normal]

  def perfil_photo
    if self.avatar.attached?
        self.avatar
    else
        'bill_gates_phrase'
    end
  end
end

app/models/youtube.rb
class Youtube
    include ActiveModel::Model
    include ActiveModel::Attributes
    include GlobalID::Identification
    include ActionText::Attachable

    attribute :id

    def self.find(id)
    new(id: id)
    end

    def thumbnail_url
    "http://i3.ytimg.com/vi/#{id}/maxresdefault.jpg"
    end

    def to_trix_content_attachment_partial_path
    "youtubes/thumbnail"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |e|
    respond_to do |format|
      format.html { redirect_to root_path, flash: { alert: "Você não possui autorização para acessar essa página!" } }
      format.json { render json: { success: false }, status: 401 }
    end
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
    skip_before_action :authenticate_user!
    
    def index
        @posts = Post.order(created_at: :DESC).page params[:page]
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_post, only: [:create]
    
    def index
    end

    def create
        @comment = Comment.new(comment_params)

        @comment.commentable = @post

        if @comment.save
            redirect_to request.referrer, notice: 'Comentário realizado com sucesso!'
        else
            redirect_to request.referrer, alert: 'Erro ao realizar comentário! Tente novamente mais tarde.'
        end
    end

    private

    def set_post
        @post = Post.friendly.find(params[:post_id])
    end

    def comment_params
        params.require(:comment).permit(:name, :email, :content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    skip_before_action :authenticate_user!
    
    def index
    end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :set_post, only: [:show, :edit, :update]

  def new
    authorize! :create, current_user
    @post = Post.new
  end

  def create
    authorize! :create, current_user
    @post = Post.new(posts_params)

    if @post.save
      redirect_to blog_index_path, notice: 'Post enviado com sucesso!'
    else
      redirect_to blog_index_path, alert: 'Erro ao enviar o post. Tente novamente mais tarde!'
    end
  end

  def edit
    authorize! :edit, current_user
  end

  def update
    authorize! :create, current_user

    if @post.update(posts_params)
      redirect_to blog_index_path, notice: 'Post atualizado com sucesso!'
    else
      redirect_to blog_index_path, alert: 'Erro ao atualizar post. Tente novamente mais tarde!'
    end
  end

  def show
    @comment = Comment.new
  end

  private

  def posts_params
    params.require(:post).permit(:title, :content, :slug, :banner, :user_id)
  end

  def set_post
    @post = Post.friendly.find(params[:id])
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/youtube_controller.rb
class YoutubeController < ApplicationController
    def show
        @youtube = Youtube.new(id: params[:id])
        
        render json: {
            sgid: @youtube.attachable_sgid,
            content: render_to_string(partial: "youtubes/thumbnail", locals: { youtube: @youtube }, formats: [:html])
        }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blog/index.html.erb
<%= javascript_pack_tag 'search' %>

<div class="container col-md-8 offset-md-2 mb-4">
  <div class="search mt-4 mb-4 text-center">
    <%= select(nil, :post_id, Post.all.collect {|mt| [ mt.title, mt.slug ] }, {:include_blank => 'Selecione sobre o que quer saber'}, id: 'dropdown', onchange: 'redirect_to_record()') %>
  </div>

  <div class="posts">
    <% @posts.each do |post| %>
      <div class="post mt-4">
        <%= image_tag post.banner_photo %>

        <div class="pt-1 page-header text-center">
          <%= post.title %>
        </div>

        <div class="post-body ps-2 pe-2">
          <%= post.content.to_plain_text.truncate(150) %>
        </div>

        <div class="see_more">
          <%= link_to 'Ver Mais', post_path(post), class: 'btn btn-danger me-3' %>
        </div>
      </div>
    <% end %>
  </div>

  <%= paginate @posts %>
</div>

<script>
  function redirect_to_record() {
    var post_index = document.getElementById("dropdown").value;
    window.location.href = "/posts/" + post_index;
  }
</script>

app/views/home/index.html.erb
<div class="fullscreen-bg">
    <iframe width="100%" height="100%" src="https://www.youtube.com/embed/XnQmiSLaqOc?autoplay=1&mute=0&controls=0"></iframe>
</div>

<style>
  body {
    background: black!important;
  }
</style>

app/views/portfolio/_instagram.html.erb
<div class="col-md-4">
  <div class="card h-100">
    <div id="instagramCarousel" class="carousel carousel-dark slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#instagramCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#instagramCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#instagramCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#instagramCarousel" data-bs-slide-to="3" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#instagramCarousel" data-bs-slide-to="4" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#instagramCarousel" data-bs-slide-to="5" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#instagramCarousel" data-bs-slide-to="6" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#instagramCarousel" data-bs-slide-to="7" aria-label="Slide 3"></button>
      </div>

      <div class="carousel-inner">
        <div class="carousel-item active" data-bs-interval="10000">
          <%= image_tag 'projects/instagram/login', class: 'd-block w-100' %>
        </div>
        
        <div class="carousel-item" data-bs-interval="2000">
          <%= image_tag 'projects/instagram/posts', class: 'd-block w-100' %>
        </div>
        
        <div class="carousel-item">
          <%= image_tag 'projects/instagram/profile', class: 'd-block w-100' %>
        </div>

        <div class="carousel-item">
          <%= image_tag 'projects/instagram/profile2', class: 'd-block w-100' %>
        </div>

        <div class="carousel-item">
          <%= image_tag 'projects/instagram/search_user', class: 'd-block w-100' %>
        </div>

        <div class="carousel-item">
          <%= image_tag 'projects/instagram/send_post', class: 'd-block w-100' %>
        </div>

        <div class="carousel-item">
          <%= image_tag 'projects/instagram/followers', class: 'd-block w-100' %>
        </div>

        <div class="carousel-item">
          <%= image_tag 'projects/instagram/sign_out', class: 'd-block w-100' %>
        </div>
      </div>
      
      <button class="carousel-control-prev" type="button" data-bs-target="#instagramCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      
      <button class="carousel-control-next" type="button" data-bs-target="#instagramCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>

    <div class="card-body">
      <h5 class="card-title"><b>Instagram Clone</b></h5>
      <p class="card-text">
        InstaClone is an application made with Ionic 3. How the name already says, 
        It's a humble Instagram's Clone made in OneBitCode Super Full Stack course.
      </p>
    </div>

    <div class="card-footer text-center">
      <%= link_to 'https://github.com/Lucasdfg07/Instagram_clone' do %>
        <%= image_tag 'github' %>
      <% end %>
    </div>
  </div>
</div>

app/views/portfolio/_nasa.html.erb
<div class="col-md-4">
  <div class="card h-100">
    <div id="nasaCarousel" class="carousel carousel-dark slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#nasaCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#nasaCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#nasaCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#nasaCarousel" data-bs-slide-to="3" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#nasaCarousel" data-bs-slide-to="4" aria-label="Slide 3"></button>
      </div>

      <div class="carousel-inner">
        <div class="carousel-item active" data-bs-interval="10000">
          <%= image_tag 'projects/nasa/home', class: 'd-block w-100' %>
        </div>
        
        <div class="carousel-item" data-bs-interval="2000">
          <%= image_tag 'projects/nasa/graphic', class: 'd-block w-100' %>
        </div>
        
        <div class="carousel-item">
          <%= image_tag 'projects/nasa/graphic_2', class: 'd-block w-100' %>
        </div>

        <div class="carousel-item">
          <%= image_tag 'projects/nasa/economy', class: 'd-block w-100' %>
        </div>

        <div class="carousel-item">
          <%= image_tag 'projects/nasa/economy_2', class: 'd-block w-100' %>
        </div>
      </div>
      
      <button class="carousel-control-prev" type="button" data-bs-target="#nasaCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      
      <button class="carousel-control-next" type="button" data-bs-target="#nasaCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>

    <div class="card-body">
      <h5 class="card-title"><b>HARMEET - NASA Space Apps Covid-19 Edition</b></h5>
      <p class="card-text">
        HARMEET was developed seeking the development of a single plataform capable of 
        gather a wide variety of data. Thereby, people will have greater access to these 
        data, which are very important for understanding the pandemic, help decision-making 
        by governments and the elaboration of solutions by the population.
      </p>
    </div>

    <div class="card-footer text-center">
      <%= link_to 'https://github.com/Lucasdfg07/NASA-space-apps-challenge' do %>
        <%= image_tag 'github' %>
      <% end %>
    </div>
  </div>
</div>

app/views/portfolio/_proffy.html.erb
<div class="col-md-4">
  <div class="card h-100">
    <div id="proffyCarousel" class="carousel carousel-dark slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#proffyCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#proffyCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#proffyCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#proffyCarousel" data-bs-slide-to="3" aria-label="Slide 4"></button>
      </div>

      <div class="carousel-inner">
        <div class="carousel-item active" data-bs-interval="10000">
          <%= image_tag 'projects/proffy/home', class: 'd-block w-100' %>
        </div>
        
        <div class="carousel-item" data-bs-interval="2000">
          <%= image_tag 'projects/proffy/teachers', class: 'd-block w-100' %>
        </div>
        
        <div class="carousel-item">
          <%= image_tag 'projects/proffy/form', class: 'd-block w-100' %>
        </div>

        <div class="carousel-item">
          <%= image_tag 'projects/proffy/form2', class: 'd-block w-100' %>
        </div>
      </div>
      
      <button class="carousel-control-prev" type="button" data-bs-target="#proffyCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      
      <button class="carousel-control-next" type="button" data-bs-target="#proffyCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>

    <div class="card-body">
      <h5 class="card-title"><b>Proffy EAD Application</b></h5>
      <p class="card-text">
        Application made with React JS into Rocketseat's Next Level Week. 
        It has the objective to improve distance learning in coronavirus pandemic times.
      </p>
    </div>

    <div class="card-footer text-center">
      <%= link_to 'https://github.com/Lucasdfg07/EAD_app' do %>
        <%= image_tag 'github' %>
      <% end %>
    </div>
  </div>
</div>

app/views/portfolio/_search_dev.html.erb
<div class="col-md-4">
  <div class="card h-100">
    <div id="search_dev_platformCarousel" class="carousel carousel-dark slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#search_dev_platformCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#search_dev_platformCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#search_dev_platformCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>

      <div class="carousel-inner">
        <div class="carousel-item active" data-bs-interval="10000">
          <%= image_tag 'projects/search_dev_platform/home', class: 'd-block w-100' %>
        </div>
        
        <div class="carousel-item" data-bs-interval="2000">
          <%= image_tag 'projects/search_dev_platform/perfil_2', class: 'd-block w-100' %>
        </div>
        
        <div class="carousel-item">
          <%= image_tag 'projects/search_dev_platform/perfil', class: 'd-block w-100' %>
        </div>
      </div>
      
      <button class="carousel-control-prev" type="button" data-bs-target="#search_dev_platformCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      
      <button class="carousel-control-next" type="button" data-bs-target="#search_dev_platformCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>

    <div class="card-body">
      <h5 class="card-title"><b>Search Dev</b></h5>
      <p class="card-text">
        Search Dev is an application to find the best devs to your company, 
        and to devs find some jobs and be more viewed. Find the bests!
      </p>
    </div>

    <div class="card-footer text-center">
      <%= link_to 'https://github.com/Lucasdfg07/SearchDev-Platform' do %>
        <%= image_tag 'github' %>
      <% end %>
    </div>
  </div>
</div>

app/views/portfolio/_spotify.html.erb
<div class="col-md-4">
  <div class="card h-100">
    <div id="spotifyCarousel" class="carousel carousel-dark slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#spotifyCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#spotifyCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#spotifyCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#spotifyCarousel" data-bs-slide-to="3" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#spotifyCarousel" data-bs-slide-to="4" aria-label="Slide 3"></button>
      </div>

      <div class="carousel-inner">
        <div class="carousel-item active" data-bs-interval="10000">
          <%= image_tag 'projects/spotify/home', class: 'd-block w-100' %>
        </div>
        
        <div class="carousel-item" data-bs-interval="2000">
          <%= image_tag 'projects/spotify/search', class: 'd-block w-100' %>
        </div>
        
        <div class="carousel-item">
          <%= image_tag 'projects/spotify/search_2', class: 'd-block w-100' %>
        </div>

        <div class="carousel-item">
          <%= image_tag 'projects/spotify/play', class: 'd-block w-100' %>
        </div>

        <div class="carousel-item">
          <%= image_tag 'projects/spotify/favorites', class: 'd-block w-100' %>
        </div>
      </div>
      
      <button class="carousel-control-prev" type="button" data-bs-target="#spotifyCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      
      <button class="carousel-control-next" type="button" data-bs-target="#spotifyCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>

    <div class="card-body">
      <h5 class="card-title"><b>Spotify Clone</b></h5>
      <p class="card-text">
        This application is an app clone of spotify made with Ruby (Back end) and ReactJS (Front end) to play musics, 
        see artist's album, their music and made your day more musicable! Did on weekcode of OneBitCode.
      </p>
    </div>

    <div class="card-footer text-center">
      <%= link_to 'https://github.com/Lucasdfg07/Spotify_clone' do %>
        <%= image_tag 'github' %>
      <% end %>
    </div>
  </div>
</div>

app/views/portfolio/_tinder.html.erb
<div class="col-md-4">
  <div class="card h-100">
    <div id="tinderCarousel" class="carousel carousel-dark slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#tinderCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#tinderCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#tinderCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#tinderCarousel" data-bs-slide-to="3" aria-label="Slide 3"></button>
      </div>

      <div class="carousel-inner">
        <div class="carousel-item active" data-bs-interval="10000">
          <%= image_tag 'projects/tinder/home', class: 'd-block w-100' %>
        </div>
        
        <div class="carousel-item" data-bs-interval="2000">
          <%= image_tag 'projects/tinder/about', class: 'd-block w-100' %>
        </div>
        
        <div class="carousel-item">
          <%= image_tag 'projects/tinder/about_2', class: 'd-block w-100' %>
        </div>

        <div class="carousel-item">
          <%= image_tag 'projects/tinder/matches', class: 'd-block w-100' %>
        </div>
      </div>
      
      <button class="carousel-control-prev" type="button" data-bs-target="#tinderCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      
      <button class="carousel-control-next" type="button" data-bs-target="#tinderCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>

    <div class="card-body">
      <h5 class="card-title"><b>Tinder Clone</b></h5>
      <p class="card-text">
        This application is a Vue.js app, based on 
        Tinder Layout and funcionality. Learn and built on the OneBitCode Bootcamp!
      </p>
    </div>

    <div class="card-footer text-center">
      <%= link_to 'https://github.com/Lucasdfg07/TinderAPP' do %>
        <%= image_tag 'github' %>
      <% end %>
    </div>
  </div>
</div>

app/views/portfolio/index.html.erb
<div class="mb-4 portfolio container">
  <div class="col-4 offset-8 background_about mt-3">
    Sobre
  </div>

  <div class="about_myself mt-4 text-center">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag 'perfil' %>
      </div>

      <div class="col-md-8 p-4">
        <p>
          Programador, criador de conteúdo e um amante de disseminar a informação!
        </p>

        <p>
          Boas vindas MÁXIMA a você que está aqui, e aprenda o máximo que puder!
        </p>

        <p>
          Caso precise, me entre no nosso grupo clicando no ícone do <b>“Whatsapp”</b> 
          no canto inferior esquerdo e me chame no nosso grupo \o/
        </p>

        <div class="text-center github_button">
          <%= link_to "https://github.com/Lucasdfg07" do %>
            <%= image_tag 'github' %>
          <% end %>

          <%= link_to "https://www.linkedin.com/in/lucasdfg07/" do %>
            <%= image_tag 'linkedin' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="col-4 background_about mt-4">
    Galeria
  </div>

  <div class="row row-cols-1 row-cols-md-3 g-4 mt-3">
    <%= render 'portfolio/proffy' %>
    <%= render 'portfolio/search_dev' %>
    <%= render 'portfolio/spotify' %>
    <%= render 'portfolio/tinder' %>
    <%= render 'portfolio/nasa' %>
    <%= render 'portfolio/instagram' %>
  </div>

  <div class="text-center github_button mt-4">
    <%= link_to "https://github.com/Lucasdfg07?tab=repositories", class: 'btn btn-dark' do %>
      See More <%= image_tag 'github' %>
    <% end %>
  </div>
</div>

app/views/youtubes/_thumbnail.html.erb
<div>
  <%= image_tag youtube.thumbnail_url, style: "max-width:400px" %>
</div>

app/views/youtubes/_youtube.html.erb
<iframe id="ytplayer" type="text/html" width="640" height="360" src="https://www.youtube.com/embed/<%= youtube.id %>" frameborder="0"></iframe>